<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html lang="en">
<head>
    
    <title>CustomerForm</title>

    
     <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <style type="text/css">
    

@import url('https://fonts.googleapis.com/css2?family=Fira+Sans&family=Patua+One&family=Poppins:wght@300;400&display=swap');
#form{
    position: relative;
    left:300px;
    
    height: 200vh;
    width: 1000px;
    background-color: #fff9e1;
}

#formBody
{
    width: 800px;
    align-items: center;
  
    margin-left: 85px;
    padding-top:20px;
}

form 
{
     display:grid;
     grid-template-columns: 2fr 2fr  ;
     grid-template-rows: 1fr 1fr;
     row-gap: 4ch;
     column-gap: 2ch;
}
 
.form-group > input
{
    border:none;
    outline:none;
    border-bottom: 2px solid black;
    background-color: #fff9e1;
    font-family: poppins;
    font-size:16px;
    
}

.Personal{
    text-align:center;
    font-family: poppins;
    font-size:20px;
    text-decoration:underline;
    

}
 
.form-group > label{
    font-family: poppins;

}

.form-group-address > input{
   
    border:none;
    outline:none;
    border-bottom: 2px solid black;
    background-color: #fff9e1;
    width: 730px;
    font-family: poppins;
    font-size:16px;
}
.form-group-address{
    font-family: poppins;
}
#address1{
    border-bottom: 2px solid black;
    width: 715px;
}
#address2{
    border-bottom: 2px solid black;
    width: 790px;
}

.form-group-address
 {
    grid-column: span 2;    
 }
 #mail  {
    grid-column: span 2;  
 }
#firstName , #lastName , #dob {
    width: 278px;
    text-align: left;
}

#amount ,  #voterID
{
    width:310px;
}
#gmail {
    width:735px;
}
#contactNumber{
    width:245px;
}
#drivingLicense{
    width:220px;
}
#panNumber{
    width:260px;
}
#aadharNumber{
    width:245px;
}
#ExecutiveName{
    width:240px;
}
#CmtDays{
    width:240px;
}

.form-group > pre{
    margin-left: 0;
    text-align: left;

    
}

#CompanyAddress{
    grid-column: span 2;  
    font-family: poppins;
    font-size: 17px;
    font-weight:700;
}

#TermsANDconditions , #sign{
    grid-column: span 2;  
    font-family:poppins;
}

#mng_sign{
    font-family:poppins;
}
#customer_sign {
    font-family:poppins;  
    text-align: right;
    
}
    
    
    </style>
   
</head>
<body>


     <div id = "form">
        <div id="FormHeader">
            <img src="/webresources/images/FormTitle.png" alt="Ideal Score" width="1000px" height="85px">
        </div>

        <div id="formBody">
        
        
			 <div class="Personal">PERSONAL DETAILS</div><br />

            <form action="insertapp" method="post">
            
            
            
            <div class="form-group" id="AppNo">
                    <label for="firstName">Application No:</label>
                    <input type="Number" id="AppNumber" name="applicationNo" placeholder="AutoGenerated" required>
            </div>
            
            <div class="form-group" id="Date">
                <label>Date</label>
                <input type="date" id="AppDate" name="date" required>
            </div>

            <div class="form-group">
                <label for="firstName">First Name:</label>
                <input type="text" id="firstName" name="firstName" placeholder="Enter your first name" required>
            </div>
    
            <div class="form-group">
                <label for="lastName">Last Name:</label>
                <input type="text" id="lastName" name="lastName" placeholder="Enter your last name" required>
            </div>
    
            <div class="form-group">
                <label>Gender:</label>
                <input type="radio" id="male" name="gender" value="male" required>
                <label for="male">Male</label>
    
                <input type="radio" id="female" name="gender" value="female" required>
                <label for="female">Female</label>

            </div>

            <div class="form-group">
                <label>Date of Birth:</label>
                <input type="date" id="dob" name="dob" required>
            </div>

            <div class="form-group">
                <label for="contactNumber">Contact Number:</label>
                <input type="tel" id="contactNumber" name="contactNumber" placeholder="Enter your contact number" required>
            </div>

            <div class="form-group-address">
                <label for="address">Address:</label>
              
                <input type="text" id="address1" name="address" placeholder="Enter your address" required><br/><br/>
                <input type="text" id="address2" name="address" placeholder="Enter your address" required>
            </div>
            
            <div class="form-group">
                <label for="panNumber">PAN Number:</label>
                <input type="text" id="panNumber" name="panNumber" placeholder="Enter your PAN number" pattern="\d{10}" title="PAN number should be 10 digits" required>
            </div>
            
            <div class="form-group">
                <label for="aadharNumber">Aadhar Number:</label>
                <input type="text" id="aadharNumber" name="aadharNumber" placeholder="Enter your Aadhar number" pattern="\d{12}" title="Aadhar number should be 12 digits" required>
            </div>
    

            <div class="form-group">
                <label for="drivingLicense">Driving License No:</label>
                <input type="text" id="drivingLicense" name="drivingLicense" placeholder="Enter your Driving License No" pattern="\d{16}" title="Driving License should be 16 digits" required>
            </div>
    
            <div class="form-group">
                <label for="voterID">Voter ID:</label>
                <input type="text" id="voterID" name="voterID" placeholder="Enter your Voter ID" required>
            </div>
    
            <div class="form-group" id="mail">
                <label for="gmail">Gmail:</label>
                <input type="email" id="gmail" name="gmail" placeholder="Enter your Gmail address" required>
            </div>

            <div class="form-group">
                <label for="amount">Amount:</label>
                <input type="number" id="amount" name="amount" placeholder="Enter the amount" required>
            </div>
            
            <div class="form-group" id="cash">
                <label>Payment Method:</label>
                <input type="radio" id="cash" name="paymentMethod" value="cash" required>
                <label for="cash">Cash</label>
    
                <input type="radio" id="online" name="paymentMethod" value="online" required>
                <label for="online">Online</label>
            </div>
    

            <div class="form-group">
                <label for="CommitedDays">Committed Days:</label>
                <input type="number" id="CmtDays" name="cmtDays" placeholder="Enter the Committed Days" required>
            </div>
            
            <div class="form-group">
                <label for="Executive Name ">Executive Name :</label>
                <input type="text" id="executiveName" name="executiveName" placeholder="Enter your Executive Name" required>
            </div>

            <div class="form-group" id="CompanyAddress">
           
                IDEAL SCORE <br/>
                First Floor,33/7-D, Pavoor Road <br/>
                Opp. Lal Creations, Padivattom, Kochi:682024 <br/>
                Contact:0484-4878089 <br/>
                9447388225
           
            </div>


            <div class="form-group" id="TermsANDconditions">
             I Authorize IDEAL SCORE to contact and clear all my credit report problems from the credit institution and financial institution . I have read and accept all the terms and conditions.
            </div>

            <div class="form-group" id="sign">
                For IDEAL SCORE Consultancy <br />
                <img src="/webresources/images/sign.png" alt="IdealScore" width="230px" height="60px"> <br />
              

            </div>

            <div class="form-group" id="mng_sign"> 
            ABHIJITH JIJI<br />
            BRANCH MANAGER
           </div>

            <div class="form-group" id="customer_sign">
                Customer Signature
            </div>


    <div class="d-grid gap-4 col-10 mx-auto">
  
  <input type="submit" class="btn btn-primary"  value="Submit"/>
    </div>

            
            
          </form>


        </div>

   </div>

</body>


</html>
